# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_base_dialog(object):
    def setupUi(self, base_dialog):
        base_dialog.setObjectName("base_dialog")
        base_dialog.resize(800, 601)
        self.label_2 = QtWidgets.QLabel(base_dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(base_dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 160, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(base_dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_6 = QtWidgets.QComboBox(base_dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(610, 110, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.pushButton = QtWidgets.QPushButton(base_dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 200, 100, 36))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(base_dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(base_dialog)
        self.label_8.setGeometry(QtCore.QRect(560, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(base_dialog)
        self.label_7.setGeometry(QtCore.QRect(340, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(base_dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(410, 110, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(base_dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(610, 150, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label = QtWidgets.QLabel(base_dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(base_dialog)
        self.label_9.setGeometry(QtCore.QRect(560, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_5 = QtWidgets.QComboBox(base_dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(410, 150, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.groupBox = QtWidgets.QGroupBox(base_dialog)
        self.groupBox.setGeometry(QtCore.QRect(310, 80, 441, 111))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBox_2 = QtWidgets.QComboBox(base_dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 110, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox = QtWidgets.QComboBox(base_dialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 60, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(base_dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(base_dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 250, 781, 341))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(-1, -1, 781, 314))
        self.tableWidget_2.setAutoScrollMargin(16)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(23)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(24)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(-1, -1, 781, 314))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(22)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox.raise_()
        self.label_2.raise_()
        self.comboBox_3.raise_()
        self.label_5.raise_()
        self.comboBox_6.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.comboBox_4.raise_()
        self.comboBox_7.raise_()
        self.label.raise_()
        self.label_9.raise_()
        self.comboBox_5.raise_()
        self.comboBox_2.raise_()
        self.comboBox.raise_()
        self.label_4.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(base_dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(base_dialog)

    def retranslateUi(self, base_dialog):
        _translate = QtCore.QCoreApplication.translate
        base_dialog.setWindowTitle(_translate("base_dialog", "基础煤种库"))
        self.label_2.setText(_translate("base_dialog", "产地"))
        self.comboBox_3.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox_3.setItemText(1, _translate("base_dialog", "1985-1990"))
        self.comboBox_3.setItemText(2, _translate("base_dialog", "1991-1995"))
        self.comboBox_3.setItemText(3, _translate("base_dialog", "1996-1998"))
        self.comboBox_3.setItemText(4, _translate("base_dialog", "1999-2002"))
        self.comboBox_3.setItemText(5, _translate("base_dialog", "2003-2005"))
        self.comboBox_3.setItemText(6, _translate("base_dialog", "2006-2010"))
        self.comboBox_3.setItemText(7, _translate("base_dialog", "2011-2015"))
        self.comboBox_3.setItemText(8, _translate("base_dialog", "2016至今"))
        self.label_5.setText(_translate("base_dialog", "热强度"))
        self.comboBox_6.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox_6.setItemText(1, _translate("base_dialog", "特高"))
        self.comboBox_6.setItemText(2, _translate("base_dialog", "高"))
        self.comboBox_6.setItemText(3, _translate("base_dialog", "中"))
        self.comboBox_6.setItemText(4, _translate("base_dialog", "低"))
        self.comboBox_6.setItemText(5, _translate("base_dialog", "特低"))
        self.pushButton.setText(_translate("base_dialog", "筛选"))
        self.label_3.setText(_translate("base_dialog", "煤种"))
        self.label_8.setText(_translate("base_dialog", "灰分"))
        self.label_7.setText(_translate("base_dialog", "硬度"))
        self.comboBox_4.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox_4.setItemText(1, _translate("base_dialog", "A级"))
        self.comboBox_4.setItemText(2, _translate("base_dialog", "B级"))
        self.comboBox_4.setItemText(3, _translate("base_dialog", "C级"))
        self.comboBox_7.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox_7.setItemText(1, _translate("base_dialog", "特高"))
        self.comboBox_7.setItemText(2, _translate("base_dialog", "高"))
        self.comboBox_7.setItemText(3, _translate("base_dialog", "中"))
        self.comboBox_7.setItemText(4, _translate("base_dialog", "低"))
        self.comboBox_7.setItemText(5, _translate("base_dialog", "特低"))
        self.label.setText(_translate("base_dialog", "筛选条件设置"))
        self.label_9.setText(_translate("base_dialog", "硫分"))
        self.comboBox_5.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox_5.setItemText(1, _translate("base_dialog", "硬煤"))
        self.comboBox_5.setItemText(2, _translate("base_dialog", "半硬优"))
        self.comboBox_5.setItemText(3, _translate("base_dialog", "半硬"))
        self.comboBox_5.setItemText(4, _translate("base_dialog", "半软"))
        self.comboBox_5.setItemText(5, _translate("base_dialog", "软煤"))
        self.groupBox.setTitle(_translate("base_dialog", "煤质分级指标"))
        self.comboBox_2.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox_2.setItemText(1, _translate("base_dialog", "焦煤"))
        self.comboBox_2.setItemText(2, _translate("base_dialog", "肥煤"))
        self.comboBox_2.setItemText(3, _translate("base_dialog", "气煤"))
        self.comboBox_2.setItemText(4, _translate("base_dialog", "1/3焦煤"))
        self.comboBox_2.setItemText(5, _translate("base_dialog", "瘦煤"))
        self.comboBox.setItemText(0, _translate("base_dialog", "所有"))
        self.comboBox.setItemText(1, _translate("base_dialog", "国内"))
        self.comboBox.setItemText(2, _translate("base_dialog", "国外"))
        self.comboBox.setItemText(3, _translate("base_dialog", "中国，山西"))
        self.comboBox.setItemText(4, _translate("base_dialog", "中国，华东"))
        self.comboBox.setItemText(5, _translate("base_dialog", "中国，其他"))
        self.comboBox.setItemText(6, _translate("base_dialog", "巴西"))
        self.label_4.setText(_translate("base_dialog", "数据年份"))
        self.tableWidget_2.setSortingEnabled(True)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("base_dialog", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("base_dialog", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("base_dialog", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("base_dialog", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("base_dialog", "5"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("base_dialog", "产地"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("base_dialog", "年份"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("base_dialog", "煤种"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("base_dialog", "热强度"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("base_dialog", "硬度"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("base_dialog", "灰分"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("base_dialog", "硫分"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("base_dialog", "CRI"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("base_dialog", "CSR"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("base_dialog", "DI150/50"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("base_dialog", "M40/M10"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("base_dialog", "Y"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("base_dialog", "X"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("base_dialog", "G"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("base_dialog", "TD"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("base_dialog", "lgMF"))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("base_dialog", "Rr"))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("base_dialog", "TI"))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("base_dialog", "Ad"))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("base_dialog", "Std"))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("base_dialog", "Vd"))
        item = self.tableWidget_2.horizontalHeaderItem(21)
        item.setText(_translate("base_dialog", "Pd(煤中)"))
        item = self.tableWidget_2.horizontalHeaderItem(22)
        item.setText(_translate("base_dialog", "K2O+Na2O(灰中)"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("base_dialog", "山西"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("base_dialog", "2016"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("base_dialog", "肥煤"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("base_dialog", "A"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("base_dialog", "硬煤"))
        item = self.tableWidget_2.item(0, 5)
        item.setText(_translate("base_dialog", "0.5"))
        item = self.tableWidget_2.item(0, 6)
        item.setText(_translate("base_dialog", "0.5"))
        item = self.tableWidget_2.item(0, 7)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 8)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 9)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 10)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 11)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 12)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 13)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 14)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 15)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 16)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 17)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 18)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 19)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 20)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 21)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget_2.item(0, 22)
        item.setText(_translate("base_dialog", "*"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("base_dialog", "历年数据"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("base_dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("base_dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("base_dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("base_dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("base_dialog", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("base_dialog", "产地"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("base_dialog", "煤种"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("base_dialog", "热强度"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("base_dialog", "硬度"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("base_dialog", "灰分"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("base_dialog", "硫分"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("base_dialog", "CRI"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("base_dialog", "CSR"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("base_dialog", "DI150/50"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("base_dialog", "M40/M10"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("base_dialog", "Y"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("base_dialog", "X"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("base_dialog", "G"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("base_dialog", "TD"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("base_dialog", "lgMF"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("base_dialog", "Rr"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("base_dialog", "TI"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("base_dialog", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("base_dialog", "Std"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("base_dialog", "Vd"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("base_dialog", "Pd(煤中)"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("base_dialog", "K2O+Na2O(灰中)"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("base_dialog", "山西"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("base_dialog", "肥煤"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("base_dialog", "A"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("base_dialog", "硬煤"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("base_dialog", "0.5"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("base_dialog", "0.5"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 14)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 15)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 16)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 17)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 18)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 19)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 20)
        item.setText(_translate("base_dialog", "*"))
        item = self.tableWidget.item(0, 21)
        item.setText(_translate("base_dialog", "*"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("base_dialog", "近十年平均数据"))

