# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_new_dialog(object):
    def setupUi(self, new_dialog):
        new_dialog.setObjectName("new_dialog")
        new_dialog.resize(800, 600)
        self.tableWidget = QtWidgets.QTableWidget(new_dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(30)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)

        self.retranslateUi(new_dialog)
        QtCore.QMetaObject.connectSlotsByName(new_dialog)

    def retranslateUi(self, new_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_dialog.setWindowTitle(_translate("new_dialog", "新煤种库"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("new_dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("new_dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("new_dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("new_dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("new_dialog", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("new_dialog", "产地"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("new_dialog", "年份"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("new_dialog", "煤种"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("new_dialog", "热强度"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("new_dialog", "硬度"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("new_dialog", "灰分"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("new_dialog", "硫分"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("new_dialog", "CRI"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("new_dialog", "CSR"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("new_dialog", "DI150/50"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("new_dialog", "M40/M10"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("new_dialog", "Y"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("new_dialog", "X"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("new_dialog", "G"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("new_dialog", "TD"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("new_dialog", "lgMF"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("new_dialog", "Rr"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("new_dialog", "TI"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("new_dialog", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("new_dialog", "Std"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("new_dialog", "Vd"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("new_dialog", "Pd(煤中)"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("new_dialog", "K2O+Na2O(灰中)"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("new_dialog", "粒级分布"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("new_dialog", "元素分析"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("new_dialog", "堆密度"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("new_dialog", "灰成分"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("new_dialog", "发热量"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("new_dialog", "全水分"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("new_dialog", "内水分"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("new_dialog", "山西"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("new_dialog", "1995"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("new_dialog", "肥煤"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("new_dialog", "A"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("new_dialog", "硬煤"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("new_dialog", "0.5"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("new_dialog", "0.5"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 14)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 15)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 16)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 17)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 18)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 19)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 20)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 21)
        item.setText(_translate("new_dialog", "*"))
        item = self.tableWidget.item(0, 22)
        item.setText(_translate("new_dialog", "*"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

